[package]
name = "bpf-tracing"
version = "0.0.7"
edition = "2024"
description = "An eBPF tracing facility that integrates neatly into Rust's tracing"
license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
xbpf = { version = "0.0.3", default-features = false, features = ["tracing"] }
